[package]
name = "dummy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = { version = "1.2.3" }
cosmwasm-std = { version = "1.2.3" }
bindings-perp = { path = "../../contracts/bindings-perp" }
shifter = { path = "../../contracts/shifter" }
controller = { path = "../../contracts/controller" }
nibiru-std = { path = "../../nibiru-std" }

[dev-dependencies]
serde_json = "1.0.95"