[package]
name = "nibiru-std"
version = "0.0.2"
edition = "2021"
description = "Nibiru Chain standard library for CosmWasm smart contracts"
authors = ["Unique Divine <realuniquedivine@gmail.com>"]

documentation = "https://docs.rs/nibiru-std"
homepage = "https://github.com/NibiruChain/cw-nibiru"
repository = "https://github.com/NibiruChain/cw-nibiru"
license-file = "LICENSE"
# license = "MIT" # only one of license, license-file is needed.

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cosmwasm-std = { version = "1.4.1", features = ["stargate"] }
cosmwasm-schema = "1.4.0"
prost = "0.12.1"
prost-types = "0.12.1"
serde = "1.0.188"
anyhow = "1"
thiserror = "1.0.49"
nibiru-macro = { path = "../packages/macro" }

# cargo run --bin script-name
# [[bin]]
# name = "rust script name"
# path = "bin/script_name.rs"