[package]
name = "nibiru-std"
version = "0.0.3"
edition = "2021"
description = "Nibiru Chain standard library for CosmWasm smart contracts"
authors = ["Unique Divine <realuniquedivine@gmail.com>"]

documentation = "https://docs.rs/nibiru-std"
homepage = "https://github.com/NibiruChain/cw-nibiru"
repository = "https://github.com/NibiruChain/cw-nibiru"
license-file = "LICENSE"
# license = "MIT" # only one of license, license-file is needed.

[features]
backtraces = ["cosmwasm-std/backtraces"]
default = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cosmwasm-std = { version = "1.4.1", features = ["stargate"] }
cosmwasm-schema = { workspace = true }
prost = "0.12.1"
prost-types = "0.12.1"
serde = "1.0.188"
anyhow = { workspace = true }
thiserror = { workspace = true }
nibiru-macro = { workspace = true }
serde_json = { workspace = true }

# cargo run --bin script-name
# [[bin]]
# name = "rust script name"
# path = "bin/script_name.rs"