[package]
name = "nibi-msig-ez"
version = "0.1.0"
edition = "2021"
keywords = ["nibiru", "blockchain", "web3", "tendermint", "multisig"]

# See more Cargo.toml key definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0.188", features = ["derive"]}
serde_json = { version = "1.0.107" }
home = "0.5"
thiserror = "1.0"
anyhow = { version = "1", features = ["backtrace"]}
nibi-dev = { path = "../nibi-dev" }

[dev-dependencies]
assert_cmd = "2"

[[bin]]
name = "msig"
path = "src/main.rs"