[package]
name        = "nibiru-ownable"
version     = { workspace = true }
description = "Utility for single-party ownership of CosmWasm smart contracts"
authors     = ["larry <gm@larry.engineer>", "Unique Divine <realuniquedivine@gmail.com>"]
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = "MIT" # only one of license, license-file is needed.

[lib]
doctest = false # disable doc tests

[dependencies]
cosmwasm-schema   = { workspace = true }
cosmwasm-std      = { workspace = true }
nibiru-ownable-derive = { workspace = true }
cw-storage-plus   = { workspace = true }
cw-utils          = { workspace = true }
thiserror         = { workspace = true }