[package]
name = "nibiru-bindings"
version = "0.2.0"
edition = "2021"
description = "Bindings for CosmWasm contracts to call into custom modules of Nibiru Chain"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
cosmwasm-std = "1.2.3"
cosmwasm-schema = "1.2.3"