name: Publish TypeScript Code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install -g @cosmwasm/ts-codegen

      - name: Generate TypeScript Clients
        run: just gen-ts

      - name: Publish TypeScript Code
        run: |
          rsync -avz ./dist/ user@your-deployment-server:/path/to/app.nibiru.fi/ts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
